### ISSUE TITLE
Looking forward your early code release~

### ISSUE THREAD

**Issue by progressforever** [DekuLiuTesla/CityGaussian#1]
Thanks for your awesome work!  Looking forward your early code release~

**Comment by DekuLiuTesla** [comment]
Thanks!

**Comment by altava-sgp** [comment]
I am also waiting for the source code.
This project is awesome ! 👍

**Comment by MickShen7558** [comment]
I am looking forward to the official code release! Could you show some release plans on the dates?

**Comment by ptg666** [comment]
Thanks!

**Comment by gwen233666** [comment]
Excellent job！Desirable to c your code release!!

**Comment by WangYu0611** [comment]
Looking forward to testing this project soon! You are awesome!

**Comment by lhc991025** [comment]
You've done a great job, looking forward to your public code!

**Comment by Suhao07** [comment]
Excellent job! What can I say ? Looking forward to your public code！

**Comment by DekuLiuTesla** [comment]
Thanks for your kind words! The source code is now available. Welcome to try it out!
