### ISSUE TITLE
Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.

### ISSUE THREAD

**Issue by zihaohi** [DekuLiuTesla/CityGaussian#10]
When I was training the MatrixCity_aerial, I encountered the following error:
Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K. If this is not desired, please explicitly specify ‘–resolution/-r’ as 1

**Comment by 7yzx** [comment]
This not a error , just telling you the input images resolution is large. You can find it in https://github.com/DekuLiuTesla/CityGaussian/blob/e37837119ff87acf910b28da5da4ed73bae69429/utils/camera_utils.py#L31

**Comment by zihaohi** [comment]
Thanks a lot!
