### ISSUE TITLE
Preparation of LoD part

### ISSUE THREAD

**Issue by ArthurXu0101** [DekuLiuTesla/CityGaussian#11]
Hi there, I got some questions about LoD part. I wonder what 's the next step after merging parallel blocks, i.e., I followed the scripts but when calling render_large_lod.py, it went wrong with failing to find "output/datasetname_40_vq". I noticed that there is a "compress" operation in the LoD illustration figure, but I couldn't find coreesponding function. In addition, the config file config/datasetname_lod.yaml contains 'lod_configs' param in model_params, which I assume is needed to run render_large_lod.py. So how should 'lod_configs' be prepared, perhaps with a 'compress' operation? I am using a custom colormap dataset stuructured like:
xxx_COLMAP
  - data_partitions (generated by the scripts)
  - images
    - jpg1
    - jpg2
  - sparse 
  - transform.json

_Originally posted by @ArthurXu0101 in https://github.com/DekuLiuTesla/CityGaussian/issues/3#issuecomment-2290493244_

**Comment by DekuLiuTesla** [comment]
Hi, thanks for your feedback. It seems that LoD Generation step is lost, which is mentioned in `Rendering with LoD` of README. LargeLightGaussian supports this part and you may need to install this submodule first.
