### ISSUE TITLE
ERROR in run_vectree_quantize_mc.sh

### ISSUE THREAD

**Issue by nurbanu170399** [DekuLiuTesla/CityGaussian#12]
When i run `bash scripts/run_vectree_quantize_mc.sh` i get the error:
`FileNotFoundError: [Errno 2] No such file or directory: './output/mc_aerial_c36_light_50_distill/point_cloud/iteration_40000/point_cloud.ply'`
seems like thers no point_cloud.ply generated. When should it be generated? I could ran the previous 2 scripts but when i look at the logs, i see:
`PIL.UnidentifiedImageError: cannot identify image file '/home/pc_5053/CityGaussian/LargeLightGaussian/data/matrix_city/aerial/train/block_all/images/1584.png'` 
Can this be the problem? Or why is there no point_cloud folder created? Should i have generated it myself? Thanks in advance

**Comment by DekuLiuTesla** [comment]
Hi, thanks for your feedback. The point cloud is generated though pruning and distillation process:
```
bash scripts/run_prune_finetune_$your_scene.sh
bash scripts/run_distill_finetune_$your_scene.sh
```
And you may need first ensure the process iscorrect. The logs will be recorded in LargeLightGaussian/logs_prune. And seems that the 1584.png is lost. Perhaps it is broken?

**Comment by nurbanu170399** [comment]
Yes 1584.png is broken. Also there are a couple of other broken images (i.e. 1491.png,1622.png,1564.png,1584.png,1598.png,1463.png). I regenerated it but keep getting the same error some are unreadable. Maybe something should be added to by-pass broken images?

**Comment by DekuLiuTesla** [comment]
I think fixing the error would be better. Losing images may lead to suboptimal results and unfair comparison.
