### ISSUE TITLE
Error when using SIBR_remoteGaussian_app to see the running training process 

### ISSUE THREAD

**Issue by 7yzx** [DekuLiuTesla/CityGaussian#13]
I run `python train_large.py --config config/mc_aerial_coarse.yaml`, and run `./SIBR_remoteGaussian_app` in another terminal then encounter this error, but the `/data/matrix_city/aerial/train/block_all` dir has `sparse/0/images.bin`, `sparse/0/cameras.bin`,' `sparse/0/point3D.bin`. 
Also I use original gaussian splatting code `train.py`, the `SIBR_remoteGaussian_app` works well. I'm confused.

```[SIBR] ##  ERROR  ##:	FILE /home/farsee2/ALL_CODE/3DGS/CityGaussian/SIBR_viewers/src/core/scene/ParseData.cpp
			LINE 560, FUNC getParsedData
			Cannot determine type of dataset at /data/matrix_city/aerial/train/block_all
[SIBR] ##  ERROR  ##:	FILE /home/farsee2/ALL_CODE/3DGS/CityGaussian/SIBR_viewers/src/projects/remote/apps/remoteGaussianUI/main.cpp
			LINE 54, FUNC resetScene
			Problem loading model info from input path data/matrix_city/aerial/train/block_all. Consider overriding path to model directory using --path.terminate called after throwing an instance of 'std::runtime_error'
```

**Comment by DekuLiuTesla** [comment]
Hi, thanks for your feedback. We didn't test our code's compatibility with SIBR_remoteGaussian_app so there might be some bugs. Instead, we check training process with wandb.  You can achieve this by simply adding a logger_config like:
```
model_params: {
    model_config: {
        name: "GaussianModel",
        kwargs: {}
    },
    sh_degree: 3,
    source_path: "data/mill19/rubble-pixsfm-resize/train",
    model_path: "",
    images: "images",
    resolution: 4,
    white_background: False,
    data_device: "cuda",
    eval: False,
    logger_config: {
        logger: "wandb",
        name: "your_exp_name",
        project: "your_project"
    }
}
```
Then you can view the training process on wandb website
