### ISSUE TITLE
did you used raw resolution photos?

### ISSUE THREAD

**Issue by smart4654154** [DekuLiuTesla/CityGaussian#14]
I have read your work and it is great. I have some confusion. Could you please answer it
I am also using data from matrix city (small city),
1.May I ask if you used Colmap to match all 7600 pieces of data at once?
2. May I ask if you trained coarse Gaussian using raw resolution photos (1920 * 1080) as input?

For question 1, I have reviewed the colmap results you provided and found that the file is quite large. I guess the answer is that colmap matched all 7600 original resolution data at once
For question 2, I find "resolution : -1"in mc_aerial_coarse.yaml. I guess the answer is that you trained coarse Gaussian using the original resolution photo as input

If I guessed wrong, please correct me. Based on my guess, I think this seems to be a difficult task
Colmap matches all 7600 pieces of data at once, which takes a long time and may cause the computer to crash
7600 original resolution photos (1920 * 1080) should be out of memory.
Looking forward to you answering my questions
Thank you very much.

**Comment by DekuLiuTesla** [comment]
Good Question! Here is the answer:

1. We use the ground-truth poses offered by MatrixCity dataset and separately match the train and test sets. And this will be faster and more robust than match from scratch. But it indeed cost a lot of time.
2. By applying resolution=-1, the image size is sampled to 1600x900, as default behavior in 3DGS. In addition, we apply CacheDataloader from [Gaussian Lightning](https://github.com/yzslab/gaussian-splatting-lightning), the memory cost is indeed acceptable, while the fine-tuning of each block can be finished within around 40 minutes
