### ISSUE TITLE
Resolution decreases during rendering

### ISSUE THREAD

**Issue by smart4654154** [DekuLiuTesla/CityGaussian#16]
Resolution decreases during rendering
Thank you very much, I encountered a bug while using the CityGaussian viewer.
This viewer is based on VISER.  I set the resolution to 1920, the photo quality to 100, and the moving resolution to 1920, the photo quality to 100.
1.During my movement, there was a noticeable decrease in resolution. When I finished moving and stopped pressing the keyboard, the rendering result suddenly became clear. 
For example ,from 28 seconds to 31 seconds in the video. This phenomenon is abnormal, theoretically the resolution should remain unchanged when moving.
2.When I finish moving and no longer press the keyboard, the rendering result is unclear. 
For example ,within 1 minute and 38 seconds of the video and beyond. This phenomenon is abnormal, theoretically the resolution should remain unchanged after the movement is completed.
Note: At other times, the resolution remains unchanged after the movement ends.
I'm not sure if this is a bug in Viser or GSPlat, can you help me? thank you.

the vedio:https://www.youtube.com/watch?v=KvWrNXg3BeA

**Comment by ArSpi** [comment]
@smart4654154 From my experience, these are not bug but some flipping, which makes the transmission of rendered images unstable. By the way, how did you get the excellent results? Mine is bad and in mess when just following the README.md step by step with RTX 3090 24G.

**Comment by smart4654154** [comment]
> @smart4654154 From my experience, these are not bug but some flipping, which makes the transmission of rendered images unstable. By the way, how did you get the excellent results? Mine is bad and in mess when just following the README.md step by step with RTX 3090 24G.

thankyou 
I just used Viewer
I use 3DGS raw code for training

**Comment by DekuLiuTesla** [comment]
> @smart4654154 From my experience, these are not bug but some flipping, which makes the transmission of rendered images unstable. By the way, how did you get the excellent results? Mine is bad and in mess when just following the README.md step by step with RTX 3090 24G.

@smart4654154 Hi, thanks for your feedback.

1. ArSpi's great reply is the case. These phenomenons are mainly attributed to VISER itself.

2. By the way, seems that there is sth wrong with block merging. Some blocks overlap with each other. I'm not sure if it is what you want. If you want to generate a demo video, this web viewer might not be a good choice. Indeed our demo is generated though script and pre-defined poses.

**Comment by smart4654154** [comment]
> > @smart4654154 From my experience, these are not bug but some flipping, which makes the transmission of rendered images unstable. By the way, how did you get the excellent results? Mine is bad and in mess when just following the README.md step by step with RTX 3090 24G.
> 
> @smart4654154 Hi, thanks for your feedback.
> 
> 1. ArSpi's great reply is the case. These phenomenons are mainly attributed to VISER itself.
> 2. By the way, seems that there is sth wrong with block merging. Some blocks overlap with each other. I'm not sure if it is what you want. If you want to generate a demo video, this web viewer might not be a good choice. Indeed our demo is generated though script and pre-defined poses.

thank you ,i have some question:
1.Did you encounter this problem during the experiment?
2.Some blocks overlap with each other.Can you take a screenshot and tell me which specific piece it is?
3.this web viewer might not be a good choice.May I ask for the reason why it is not recommended. Can you recommend a Viewer?
4. Indeed our demo is generated though script and pre-defined poses. Where can I see your demo specifically
thank you

**Comment by smart4654154** [comment]
By the way, have you encountered this error before?
CUDA error: an illegal memory access was encountered 


This error is quite common,
https://github.com/graphdeco-inria/gaussian-splatting/issues?q=illegal+memory+
But I didn't solve it.

**Comment by DekuLiuTesla** [comment]
> > > @smart4654154 From my experience, these are not bug but some flipping, which makes the transmission of rendered images unstable. By the way, how did you get the excellent results? Mine is bad and in mess when just following the README.md step by step with RTX 3090 24G.
> > 
> > 
> > @smart4654154 Hi, thanks for your feedback.
> > 
> > 1. ArSpi's great reply is the case. These phenomenons are mainly attributed to VISER itself.
> > 2. By the way, seems that there is sth wrong with block merging. Some blocks overlap with each other. I'm not sure if it is what you want. If you want to generate a demo video, this web viewer might not be a good choice. Indeed our demo is generated though script and pre-defined poses.
> 
> thank you ,i have some question: 1.Did you encounter this problem during the experiment? 2.Some blocks overlap with each other.Can you take a screenshot and tell me which specific piece it is? 3.this web viewer might not be a good choice.May I ask for the reason why it is not recommended. Can you recommend a Viewer? 4. Indeed our demo is generated though script and pre-defined poses. Where can I see your demo specifically thank you

@smart4654154 Here are the answers:
1. Yes, in my experiments the web viewer has similar performance
2. This part merges two buildings from different blocks
![image](https://github.com/user-attachments/assets/9837d516-222e-431b-98ee-ab2bcd4f6123)
3&4. As you have observed, web viewer leads to floating resolution. If you need a demo like what presented on our [project page](https://dekuliutesla.github.io/citygs/), try to specify your own scripts.
5. From my experience, this CUDA error is mainly related to the rasterizer. Perhaps inputs are on different devices?

**Comment by smart4654154** [comment]
> > > > @smart4654154 From my experience, these are not bug but some flipping, which makes the transmission of rendered images unstable. By the way, how did you get the excellent results? Mine is bad and in mess when just following the README.md step by step with RTX 3090 24G.
> > > 
> > > 
> > > @smart4654154 Hi, thanks for your feedback.
> > > 
> > > 1. ArSpi's great reply is the case. These phenomenons are mainly attributed to VISER itself.
> > > 2. By the way, seems that there is sth wrong with block merging. Some blocks overlap with each other. I'm not sure if it is what you want. If you want to generate a demo video, this web viewer might not be a good choice. Indeed our demo is generated though script and pre-defined poses.
> > 
> > 
> > thank you ,i have some question: 1.Did you encounter this problem during the experiment? 2.Some blocks overlap with each other.Can you take a screenshot and tell me which specific piece it is? 3.this web viewer might not be a good choice.May I ask for the reason why it is not recommended. Can you recommend a Viewer? 4. Indeed our demo is generated though script and pre-defined poses. Where can I see your demo specifically thank you
> 
> @smart4654154 Here are the answers:
> 
> 1. Yes, in my experiments the web viewer has similar performance
> 2. This part merges two buildings from different blocks
>    ![image](https://private-user-images.githubusercontent.com/48622392/359763276-9837d516-222e-431b-98ee-ab2bcd4f6123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjA1NzcsIm5iZiI6MTcyNDIyMDI3NywicGF0aCI6Ii80ODYyMjM5Mi8zNTk3NjMyNzYtOTgzN2Q1MTYtMjIyZS00MzFiLTk4ZWUtYWIyYmNkNGY2MTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA2MDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzRiZjc2ZDk5YmI3ZWI0N2NjYjhhNDQ4Y2QyOTgxMWVkNjE3NDAzYWU0MzVkMGZkMjIwYmQ5M2ZmZDQ0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.soytAjMVl4pL5CemhWeyBcsaAXvPcNZDTI9atS9WRRM)
>    3&4. As you have observed, web viewer leads to floating resolution. If you need a demo like what presented on our [project page](https://dekuliutesla.github.io/citygs/), try to specify your own scripts.
> 3. From my experience, this CUDA error is mainly related to the rasterizer. Perhaps inputs are on different devices?

thank you 
 3&4. As you have observed, web viewer leads to floating resolution. If you need a demo like what presented on our [project page](https://dekuliutesla.github.io/citygs/), try to specify your own scripts.
Q1:You are using a web viewer (viewer), rendering photos by scripts, and synthesizing videos,is it right?

From my experience, this CUDA error is mainly related to the rasterizer. Perhaps inputs are on different devices?
Q2:
Perhaps inputs are on different devices?do you mean some data's device is cpu,and some data's device is cuda?
I can browse normally in the web viewer (viewer), but after about 30 seconds, there will be an error message:CUDA error: an illegal memory access was encountered. Do you know what the reason is?

Q3:web viewer leads to floating resolution.A decrease in resolution can lead to a deterioration in the effect.I need to show others in real-time, do you have any suggestions?
thank you
