### ISSUE TITLE
Setting max_block_id 

### ISSUE THREAD

**Issue by nurbanu170399** [DekuLiuTesla/CityGaussian#17]
First of all, thank you for replying every question. My question is, how does `max_block_id ` affect the training process exactly ? If i set it too high or too low, what happens? I set it to 35 and it seems like the training is taking forever with 315 images.

**Comment by ArSpi** [comment]
In my opinion, `max_block_id` means how many sub-regions the scene is divided. Because regions are numbered from 0, `max_block_id` equals the number of regions minus 1.

**Comment by DekuLiuTesla** [comment]
@nurbanu170399 Good question. In addition to @ArSpi 's nice answer, Table S3 of our paper examines how block number influences performance and data assignment. And under a normal case, the training image number varies among blocks.

**Comment by nurbanu170399** [comment]
Thank you so much!
