### ISSUE TITLE
Point_cloud.ply file empty

### ISSUE THREAD

**Issue by Assaciry** [DekuLiuTesla/CityGaussian#20]
Hi, thank you for your work. I had a problem training on my custom dataset. I adjusted the `block_dim`, `aabb `and `max_block_id `according to my dataset. I did the coarse training and data_partition. Seems like there is no problem. When i trained all the cells (16), there are point_cloud.ply files saved under `point_cloud_blocks ` but they are empty and only containing header except cell number 10. I checked if there are any gaussian points detected, and there are. Points exist for all cells but they do not get saved to point_cloud.ply files except cell10. I dont know why. Can there be a problem with save function? Thank you in advance.

**Comment by DekuLiuTesla** [comment]
Hi, thanks for your feedback. The result seems to be weird. I will test the merge.py and check if there is any bug.
