### ISSUE TITLE
How to determine aabb for custom dataset.

### ISSUE THREAD

**Issue by nurbanu170399** [DekuLiuTesla/CityGaussian#23]
Hi, i am using custom dataset and my interested area is a 550x500m and 100m height area. What should be a good `block_dim `and `aabb `for this dataset? I set the `block_dim `to (3,3,1). But i did not quite understand the logic of setting aabb. What should my aabb be?

**Comment by DekuLiuTesla** [comment]
Hi, this part is included in our latest [Custom Dataset Instruction](https://github.com/DekuLiuTesla/CityGaussian/blob/main/doc/custom_dataset.md). Please refer to it.
