### ISSUE TITLE
Bug: Unable to get default aabb in viewer.py when viewing lod 

### ISSUE THREAD

**Issue by Sunnyhong0326** [DekuLiuTesla/CityGaussian#28]
Hi, when I run my custom dataset and view the viewer through viewer.py, the error occurs
![image](https://github.com/user-attachments/assets/a1758229-ba6d-4781-9aef-b7152cc986a1)
I type the command as following: python viewer.py config/my_customdata_lod.yaml
This is the simular issue of [issue#27](https://github.com/DekuLiuTesla/CityGaussian/issues/27) , seems forget to add logic to get default aabb

**Comment by DekuLiuTesla** [comment]
Hi~. Please check [here ](https://github.com/DekuLiuTesla/CityGaussian/blob/215dfd3e9a9e75279d4345780af6c4efdda04877/render_large_lod.py#L91). Has this modification added and worked?

**Comment by Sunnyhong0326** [comment]
Yes, render_large_lod.py works, but **viewer.py doesn't work.** 
I can view the web viewer (viewer.py) by explicit type the aabb specified in my_customdata_aabb.npy in configuration file, but when user commment out aabb line in my_customdata_lod.yaml it causes error (it should automatically get default aabb when user comment out this line)

**Comment by DekuLiuTesla** [comment]
Thanks for your valuable feedback! This problem has now been fixed. Try the new viewer!

**Comment by Sunnyhong0326** [comment]
Thanks! It works now!
