### ISSUE TITLE
Bug: Unable to render images in render_large_lod.py without custom_test argument

### ISSUE THREAD

**Issue by Sunnyhong0326** [DekuLiuTesla/CityGaussian#29]
Hi, when I run python render_large_lod.py without custom_test (I want to render training images so I skip custom_test argument), the error occurs:
![image](https://github.com/user-attachments/assets/e6094c1c-2512-4f8c-b137-0d6577a85036)
It seems that in line [#123](https://github.com/DekuLiuTesla/CityGaussian/blob/735da08ec0992b17adce4ca5f24026b54fd726e7/render_large_lod.py#L123) and in line [#126](https://github.com/DekuLiuTesla/CityGaussian/blob/735da08ec0992b17adce4ca5f24026b54fd726e7/render_large_lod.py#L126) you forget to add the first argument: dataset
I run it successfully by adding the first argument dataset in [render_set() ](https://github.com/DekuLiuTesla/CityGaussian/blob/735da08ec0992b17adce4ca5f24026b54fd726e7/render_large_lod.py#L123)function

**Comment by DekuLiuTesla** [comment]
Thansk for your reminding! All the datasets we used have separate test set so we didn't notice this problem. This bug is now fixed.
