### ISSUE TITLE
FileNotFoundError after training

### ISSUE THREAD

**Issue by valenrach** [DekuLiuTesla/CityGaussian#30]
Congratulations for such a perfect study ! I am facing an issue. When I execute the run_citygs.sh on small MatrixCity : 

![image](https://github.com/user-attachments/assets/06a74396-cbea-42c6-90b0-2f53c2fb2302)

it trains and produces the folders under output folder:

![image](https://github.com/user-attachments/assets/9935d493-3401-4b5e-9dcc-7b5084761e13)

but they are empty inside:

![image](https://github.com/user-attachments/assets/e82e7b79-8f29-471f-ab21-9cd0f62892e8)

therefore, it produces this error during merge.py :

![image](https://github.com/user-attachments/assets/d0a0aa5f-ce13-496e-99b5-a3b051caf601)

Can you help me to solve this issue, please?

Best regards

**Comment by DekuLiuTesla** [comment]
Hi, @valenrach , what's the report when running per-cell training? is there anything wrong?

**Comment by Arexsika** [comment]
I also found FileNotFoundError, but it happened during Lod training.
![1726217381809](https://github.com/user-attachments/assets/8feaead4-cbca-4aca-a189-9c75435a29d8)

**Comment by valenrach** [comment]
Many thanks for your quick response. I am running on single RTX 4090 GPU.  Here is my training logs:

(citygs) oem@valenrach:~/CityGaussian-main$ bash scripts/run_citygs.sh
GPU 0 is available.
Optimizing 
Output folder: ./output/mc_aerial_coarse [13/09 13:51:16]
Reading camera 5621/5621 [13/09 13:51:24]
Train cameras: 5621, Test cameras: 0 [13/09 13:51:24]
Number of points at initialisation :  3826641 [13/09 13:51:24]
#17046 dataloader seed to 42 [13/09 13:51:25]
Training progress:   0%|                                                                                                                                                         | 0/30000 [00:00<?, ?it/s][ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [13/09 13:51:25]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [13/09 13:51:25]
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1 [13/09 13:51:25]
#17046 caching images (1st: 2899): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 99.16it/s]
#17046 caching images (1st: 22): 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 99.45it/s]
#17046 caching images (1st: 253): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 99.82it/s]
#17046 caching images (1st: 132): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 99.78it/s]
#17046 caching images (1st: 4916): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 100.47it/s]
#17046 caching images (1st: 2887): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 102.25it/s]
#17046 caching images (1st: 1510): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 99.09it/s]
#17046 caching images (1st: 3672): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 99.52it/s]
#17046 caching images (1st: 5335): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 100.53it/s]
#17046 caching images (1st: 790): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:05<00:00, 98.54it/s]
#17046 caching images (1st: 434): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 501/501 [00:05<00:00, 98.20it/s]
#17046 caching images (1st: 163): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 180.89it/s]
#17046 caching images (1st: 758): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 185.32it/s]
#17046 caching images (1st: 2746): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 186.04it/s]
Training progress:  23%|█████████████████████████████▍                                                                                                | 7000/30000 [09:11<22:51, 16.77it/s, Loss=0.1821689]
[ITER 7000] Evaluating train: L1 0.09011364281177521 PSNR 18.28027687072754 [13/09 14:00:40]

[ITER 7000] Saving Gaussians [13/09 14:00:40]
#17046 caching images (1st: 1126): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 192.32it/s]
#17046 caching images (1st: 564): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 187.65it/s]
#17046 caching images (1st: 3718): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 182.92it/s]
#17046 caching images (1st: 3896): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 188.98it/s]
#17046 caching images (1st: 2288): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 182.90it/s]
#17046 caching images (1st: 496): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 179.58it/s]
#17046 caching images (1st: 1411): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 183.76it/s]
#17046 caching images (1st: 871): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 501/501 [00:02<00:00, 182.42it/s]
#17046 caching images (1st: 4848): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 181.51it/s]
#17046 caching images (1st: 5517): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 184.71it/s]
#17046 caching images (1st: 4981): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 188.34it/s]
#17046 caching images (1st: 4922): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 181.81it/s]
#17046 caching images (1st: 2204): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 185.45it/s]
#17046 caching images (1st: 897): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:02<00:00, 187.56it/s]
Training progress:  48%|███████████████████████████████████████████████████████████▌                                                                 | 14300/30000 [18:49<23:06, 11.32it/s, Loss=0.1387621]Traceback (most recent call last):
  File "/home/oem/CityGaussian-main/train_large.py", line 310, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/oem/CityGaussian-main/train_large.py", line 160, in training
    gaussians.densify_and_prune(opt.densify_grad_threshold, 0.005, scene.cameras_extent, size_threshold)
  File "/home/oem/CityGaussian-main/scene/gaussian_model.py", line 408, in densify_and_prune
    self.densify_and_split(grads, max_grad, extent)
  File "/home/oem/CityGaussian-main/scene/gaussian_model.py", line 383, in densify_and_split
    self.densification_postfix(new_xyz, new_features_dc, new_features_rest, new_opacity, new_scaling, new_rotation)
  File "/home/oem/CityGaussian-main/scene/gaussian_model.py", line 351, in densification_postfix
    optimizable_tensors = self.cat_tensors_to_optimizer(d)
  File "/home/oem/CityGaussian-main/scene/gaussian_model.py", line 333, in cat_tensors_to_optimizer
    group["params"][0] = nn.Parameter(torch.cat((group["params"][0], extension_tensor), dim=0).requires_grad_(True))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.14 GiB (GPU 0; 23.54 GiB total capacity; 16.44 GiB already allocated; 696.38 MiB free; 21.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Training progress:  48%|███████████████████████████████████████████████████████████▌                                                                 | 14300/30000 [18:49<20:40, 12.66it/s, Loss=0.1387621]
GPU 0 is available.
Output folder: ./output/mc_aerial_c36 [13/09 14:10:16]
Reading camera 5621/5621 [13/09 14:10:26]
Train cameras: 5621, Test cameras: 0 [13/09 14:10:26]
Traceback (most recent call last):
  File "/home/oem/CityGaussian-main/data_partition.py", line 151, in <module>
    scene = LargeScene(lp, gaussians, shuffle=False)
  File "/home/oem/CityGaussian-main/scene/__init__.py", line 168, in __init__
    self.gaussians.load_ply(os.path.join(self.pretrain_path, "point_cloud.ply"))
  File "/home/oem/CityGaussian-main/scene/gaussian_model.py", line 229, in load_ply
    plydata = PlyData.read(path)
  File "/home/oem/.conda/envs/citygs/lib/python3.9/site-packages/plyfile.py", line 401, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/home/oem/.conda/envs/citygs/lib/python3.9/site-packages/plyfile.py", line 481, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: 'output/mc_aerial_coarse/point_cloud/iteration_30000/point_cloud.ply'
GPU 0 is available. Starting training block '0'
Optimizing 
Output folder: ./output/mc_aerial_c36/cells/cell0 [13/09 14:10:28]
Traceback (most recent call last):
  File "/home/oem/CityGaussian-main/train_large.py", line 310, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/oem/CityGaussian-main/train_large.py", line 44, in training
    scene = LargeScene(dataset, gaussians)
  File "/home/oem/CityGaussian-main/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/home/oem/.conda/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/matrix_city/aerial/train/block_all/data_partitions/mc_aerial_c36.npy'
GPU 0 is available. Starting training block '1'
Optimizing 
Output folder: ./output/mc_aerial_c36/cells/cell1 [13/09 14:12:28]
Traceback (most recent call last):
  File "/home/oem/CityGaussian-main/train_large.py", line 310, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/oem/CityGaussian-main/train_large.py", line 44, in training
    scene = LargeScene(dataset, gaussians)
  File "/home/oem/CityGaussian-main/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/home/oem/.conda/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/matrix_city/aerial/train/block_all/data_partitions/mc_aerial_c36.npy'
GPU 0 is available. Starting training block '2'
Optimizing 
Output folder: ./output/mc_aerial_c36/cells/cell2 [13/09 14:14:28]
Traceback (most recent call last):
  File "/home/oem/CityGaussian-main/train_large.py", line 310, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/home/oem/CityGaussian-main/train_large.py", line 44, in training
    scene = LargeScene(dataset, gaussians)
  File "/home/oem/CityGaussian-main/scene/__init__.py", line 123, in __init__
    partition = np.load(os.path.join(args.source_path, "data_partitions", f"{args.partition_name}.npy"))[:, args.block_id]
  File "/home/oem/.conda/envs/citygs/lib/python3.9/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/matrix_city/aerial/train/block_all/data_partitions/mc_aerial_c36.npy'
GPU 0 is available. Starting training block '3'

**Comment by DekuLiuTesla** [comment]
Hi, @valenrach ,it's due to CUDA Out of Memory error. Please refer to https://github.com/DekuLiuTesla/CityGaussian/issues/9#issuecomment-2290538506
