### ISSUE TITLE
vRAM keep increase using viewer

### ISSUE THREAD

**Issue by meidachen** [DekuLiuTesla/CityGaussian#34]
Thank you so much for your great work! I was trying out your process on my large-scale datasets and noticed while visualizing the trained GS, vRAM continued to increase while I'm moving around the scene, I'm wondering if you could give me some hints on why this is happening and if you may have some quick solution about this.

Thank you!

**Comment by DekuLiuTesla** [comment]
Hi, @meidachen , this phenomenon is possible if you are enlarging your field of view or turning to view complex regions, as more Gaussians participate in rendering. You could try to use torch.empty_cache  (may slower down the viewer) or use compressed version of Gaussian to avoid OOM problem.

**Comment by meidachen** [comment]
Hi @DekuLiuTesla ,

Thanks for your responses, empty_cache did work but it also slowed down the rendering as you mentioned. I'm wondering how I should use a compressed version of Gaussian? I'm currently running the render_lod, and if I understand it correctly, the all compressed Gaussian (from light Gaussian) were first un-compressed to become normal gaussian in your process, and rendered using the original Gaussian process. Is rendering using the compressed version of Gaussian already implemented in your github which I missed?

Thanks for your help!

**Comment by DekuLiuTesla** [comment]
Hi @meidachen , a practical way is to use only one LoD level in `lod_configs`. In this way, it will behave as rendering the compressed version of Gaussian.

**Comment by meidachen** [comment]
@DekuLiuTesla , I'm wondering if "rendering the compressed version of Gaussian" is the same as rendering the original version (.ply) in terms of vRAM usage?
Since then, the compressed version of Gaussian has been converted into regular Gaussian before rendering. Please correct me if I'm getting this part incorrect. Thanks!
