### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by lhc991025** [DekuLiuTesla/CityGaussian#36]
Thank you very much for your excellent work. When I was training with A5000 (24G), I encountered CUDA out of memory. May I ask what device you are using?
![1726330806527](https://github.com/user-attachments/assets/31c5c1a8-00f6-4981-b129-efffa30369fa)

**Comment by DekuLiuTesla** [comment]
Hi, similar problem is here https://github.com/DekuLiuTesla/CityGaussian/issues/9

**Comment by lhc991025** [comment]
> Hi, similar problem is here #9

When I set the max_cache_num to 256, it still appeared CUDA out of memory

**Comment by Wting0106** [comment]
I have the same problem

**Comment by jjkingy** [comment]
Do you solve the problem? I have the same errror
