### ISSUE TITLE
Could you provide your CPU memory?

### ISSUE THREAD

**Issue by ArSpi** [DekuLiuTesla/CityGaussian#41]
When I run `run_citygs_lod.sh` on the `residence` dataset, three `prune` programs run parallel, and each of them uses about 170G Memory of CPU, while I only have a 500G memory, which cause an `allocate memory` error. @DekuLiuTesla

**Comment by ArSpi** [comment]
I check the code and confirm that `viewpoint_cam = loadCam(dataset, viewpoint_cam.uid, viewpoint_cam, 1)` in `prune_list()` causes all of the question. In `loadcam()`, `resized_image_rgb = PILtoTorch(cam_info.image, resolution)` costs about 70M and loops `len(viewpoint_stack)` times, which may cause memory leak and finally cost 170G memory.

**Comment by DekuLiuTesla** [comment]
Hi~, @ArSpi , thanks for your valuable feedback. Our CPU memory is over 500G, and thus didn't notice this problem. `prune_list` iterates over all views and it seems that images are loaded and stored in CPU memory. A possible solution is to use our loadCam_woImage in `prune_list`.
