### ISSUE TITLE
CUDA out of memory error during train_large

### ISSUE THREAD

**Issue by Richardder** [DekuLiuTesla/CityGaussian#42]
My GPU is RTX 3090, when I run the train_large.py, it always fails.
Should I use GPU with 40G or larger GPU memory?
![截屏2024-09-25 22 16 57](https://github.com/user-attachments/assets/a5869c40-b6cc-4605-88c0-faac42ac7e78)

**Comment by ArSpi** [comment]
Please check #9.

**Comment by Richardder** [comment]
> Please check #9.

I tried to set the max_cache_num=256 and resolution=4, it still didn't work.

**Comment by Richardder** [comment]
It turns out that it's the RAM overflow, not the GPU memory.

**Comment by jjkingy** [comment]
> It turns out that it's the RAM overflow, not the GPU memory.
please tell me how did you solve this problem.Thanks

**Comment by Richardder** [comment]
> > It turns out that it's the RAM overflow, not the GPU memory.
> > please tell me how did you solve this problem.Thanks

You can follow the #53 issue
