### ISSUE TITLE
Many floating Gauss points in the sky

### ISSUE THREAD

**Issue by zwl995** [DekuLiuTesla/CityGaussian#43]
Hello, I used the configuration file you provided to train the rubble_c9_r4 scenario in the mill19 dataset, but the result I got was more clutter in the air. Can you help me see what caused it?
![微信截图_20240927101642](https://github.com/user-attachments/assets/7518a504-5a7a-4326-8234-0ba730f1a81a)

**Comment by yzslab** [comment]
This dataset contains images in various lighting conditions. The model simply adds floaters to overfit such lighting differences.

**Comment by DekuLiuTesla** [comment]
Hi, @zwl995, during the development of our CityGaussian, the influence of light changes is ignored and thus can lead to undesirable floaters.  To remove them, a favorable practice is introducing appearance embedding like VastGaussian.
