### ISSUE TITLE
运行程序时无法调用多卡训练

### ISSUE THREAD

**Issue by xiehao-ai** [DekuLiuTesla/CityGaussian#44]
`run_citygs.sh`脚本中的多gpu指定无效，训练时只使用了一张卡，请问有碰到过这种情况吗

**Comment by DekuLiuTesla** [comment]
Hi~ @xiehao-ai , is there any cues about the error? The GPU selection part will ignore GPUS with available VRAM lower than certain threshold.

**Comment by DuHao55** [comment]
I have the same error, the logs indicate that there is only one card available for training. Please tell me how to solve it.

**Comment by DuHao55** [comment]
I'm also experiencing the inability to multi-card when running the run_citygs.sh script on the server, and training with only one card for training. How can I fix this please?
