### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by DuHao55** [DekuLiuTesla/CityGaussian#48]
Nice work! I have successfully trained the rubble dataset following the readme. After training, I found that the FPS in cost.json of rubble_c9_r4 and rubble_c9_r4_lod are not much different(same GPUs), and I see that Table2 of the paper says that LoD will improve the FPS.
![7fc08bc8dd884a42de31c453a92a904](https://github.com/user-attachments/assets/af572ea8-f321-4efb-9a11-a3571806399b)

By the way, I would like to use citygaussian for reconstruction of bridge piers, here is my sparse point cloud data, the diameter of the piers is 1.2m and the height is 5m (Y axis). What would you suggest to set aabb and block_dim to?
![f21444f29b25f0dd3d4dab46fc481b6](https://github.com/user-attachments/assets/9e8ed6ee-2116-47a1-9853-8f77fe7253ec)

**Comment by DekuLiuTesla** [comment]
Hi, @DuHao55, thanks for your feedback. On the one hand, the FPS testing is related to the concurrent progress on the GPU. For a fair evaluation, please ensure that the GPU for testing is empty. On the other hand, for relative small scenes like Rubble or SciArt, the effect of LoD may not be that significant, as shown in Table S1 of the Appendix. Finally, for this bridge case, you can use our default aabb as suggested in the custom dataset instruction. For block_dim, you can divide only the y-axis and apply 5 blocks.
