### ISSUE TITLE
memory occupation problem

### ISSUE THREAD

**Issue by muzol132126** [DekuLiuTesla/CityGaussian#53]
That's an excellent work!
When running the code below with the Mill19 dataset, I encountered a problem of memory and swap space occupation. Specifically, as the program runs, the system's memory usage continues to increase. Eventually, the program is automatically killed by the system due to memory exhaustion and cannot complete the task normally.
```
CUDA_VISIBLE_DEVICES=0 python train_large.py --config config/building_coarse.yaml
```
How could I solve this problem?

**Comment by DekuLiuTesla** [comment]
Hi, @muzol132126, a practical way is to adjust max_cache_num to fit the memory limit, as explained in FAQ.

**Comment by muzol132126** [comment]
Thanks for your reply!
I have already tried adjusting the max_cache_num. I even set it to 32. The default value is 512. However, the program still gets killed due to memory overflow. I have 64GB of memory and 61GB of swap space on Ubuntu 20.04. 
The problem occurs when I read about 1600 images of the building dataset. Additionally, when using the mill19 aerial dataset, this issue doesn't appear.

**Comment by DekuLiuTesla** [comment]
@muzol132126 Have you downsampled the images? Does the training successfully start when 32 images are read?

**Comment by yzslab** [comment]
Looks like the loaded images can not be garbage collected, since they are all stored in the `image` field of the list of the `CameraInfo` here:
https://github.com/DekuLiuTesla/CityGaussian/blob/11ece7d88627e3a85f0979b502dd500c526f4367/scene/datasets.py#L26

Here is a simple workaround:
```diff
diff --git a/utils/camera_utils.py b/utils/camera_utils.py
index d6807fa..e1bb9ac 100644
--- a/utils/camera_utils.py
+++ b/utils/camera_utils.py
@@ -14,11 +14,14 @@ import numpy as np
 from utils.general_utils import PILtoTorch
 from utils.graphics_utils import fov2focal
 from transforms3d.euler import euler2mat, mat2euler
+from PIL import Image
 
 WARNED = False
 
 def loadCam(args, id, cam_info, resolution_scale):
-    orig_w, orig_h = cam_info.image.size
+    pil_image = Image.open(cam_info.image_path)
+
+    orig_w, orig_h = pil_image.size
 
     if args.resolution in [1, 2, 4, 8]:
         resolution = round(orig_w/(resolution_scale * args.resolution)), round(orig_h/(resolution_scale * args.resolution))
@@ -39,7 +42,7 @@ def loadCam(args, id, cam_info, resolution_scale):
         scale = float(global_down) * float(resolution_scale)
         resolution = (int(orig_w / scale), int(orig_h / scale))
 
-    resized_image_rgb = PILtoTorch(cam_info.image, resolution)
+    resized_image_rgb = PILtoTorch(pil_image, resolution)
 
     gt_image = resized_image_rgb[:3, ...]
     loaded_mask = None
@@ -47,6 +50,8 @@ def loadCam(args, id, cam_info, resolution_scale):
     if resized_image_rgb.shape[1] == 4:
         loaded_mask = resized_image_rgb[3:4, ...]
 
+    pil_image.close()
+
     return Camera(colmap_id=cam_info.uid, R=cam_info.R, T=cam_info.T, 
                   FoVx=cam_info.FovX, FoVy=cam_info.FovY, 
                   image=gt_image, gt_alpha_mask=loaded_mask,
```

**Comment by muzol132126** [comment]
@yzslab Thank you very much for your answer. It has successfully resolved the issue I was facing.

**Comment by DekuLiuTesla** [comment]
This bug has been fixed in latest updates.
