### ISSUE TITLE
Questions for preparing UrbanScene3D Mill19 MatrixCity Dataset

### ISSUE THREAD

**Issue by Sunnyhong0326** [DekuLiuTesla/CityGaussian#54]
Hi, you have provided the COLMAP results of the 3 datasets.
However, I am wondering if I need to undistort the images from the 3 datasets.
If so, the COLMAP results you provided is **undistorted** version, not distorted version.
We need to undistorted the images using the distorted version of COLMAP results, which is this line https://github.com/DekuLiuTesla/CityGaussian/blob/11ece7d88627e3a85f0979b502dd500c526f4367/convert_cam.py#L83

**Comment by DekuLiuTesla** [comment]
Hi, @Sunnyhong0326, this is a good question.  Your suggestion is correct, we do conduct undistortion in COLMAP result generation, and for a proper usage, the image distortion should be applied. We will add a hint to the repo.

**Comment by Sunnyhong0326** [comment]
Hi, thanks for clarifying!
However, if we need to undistort images, we will need the distorted COLMAP not the one you provided (which is the undistorted COLMAP).
As below is the COLMAP I downloaded from yours, the one you provided is already a PINHOLE Camera, we will need the OPENCV Camera (with distorted parameters) to undistort images. 
![image](https://github.com/user-attachments/assets/fccc8867-e9f3-4050-86a3-d67c4b98ebe0)

**Comment by DekuLiuTesla** [comment]
Hi, @Sunnyhong0326, you are right, to finish undistortion the distorted COLMAP is required. But for many reasons we are unable to provide this part. However, we observe that the undistortion only leads to minimal changes to images. In other words, without the undistortion, the provided COLMAP results can fit the original images well. So approximately, the undistortion step can be skipped   when using the provided COLMAP results.

**Comment by Sunnyhong0326** [comment]
This information is useful! Thanks!
