### ISSUE TITLE
Too many folaters

### ISSUE THREAD

**Issue by DuHao55** [DekuLiuTesla/CityGaussian#55]
Thank you for your outstanding work, I have successfully run through my own bridge pier dataset (close to 5000 sheets) using the parameters configured by rubble with the following results:
![image](https://github.com/user-attachments/assets/bd6c1371-1216-47fa-84e5-e93fb14e4a27)
However, in the generated model, I noticed that the surface of the bridge pier appeared to have a lot of floaters, which resulted in a non-smooth surface and also resulted in the reconstruction. This is the image I captured with the robot, captured closer to the surface of the bridge pier(On the robot I used light boards, resulting in equal lighting for all images).
![_h0_l1](https://github.com/user-attachments/assets/f7b890e6-3917-4318-b9cf-96334a7cba84)
This is what I got from my rendering.
![00000](https://github.com/user-attachments/assets/2801a30a-7904-457e-950f-52603d5f0fe9)
The results don't seem to work very well for weak textures and there are too many floaters.
What is the solution to this, please? Can I make it work better by adjusting the parameters?

**Comment by yzslab** [comment]
I think you can try smaller the LR of the xyz, and disable the opacity reseting.

**Comment by DuHao55** [comment]
Sorry, I am a novice. Do you mean to set a smaller position inti LR? Does Disable the opacity mean I just need to comment out these two lines of code in train_large.py?https://github.com/DekuLiuTesla/CityGaussian/blob/11ece7d88627e3a85f0979b502dd500c526f4367/train_large.py#L164

**Comment by yzslab** [comment]
> Sorry, I am a novice. Do you mean to set a smaller position inti LR? Does Disable the opacity mean I just need to delete these two lines of code in train_large.py?
> 
> https://github.com/DekuLiuTesla/CityGaussian/blob/11ece7d88627e3a85f0979b502dd500c526f4367/train_large.py#L164

* Both the init and final LR
* Right

**Comment by DuHao55** [comment]
I have retrained the model as per your comments and turning down the init and final LR did improve the model performance (PSNR improved by 1.5). And when I continued to make disable the opacity reseting, the model performed a little and I observed that it seems to floaters more.
![00000](https://github.com/user-attachments/assets/5e2b51f1-c93b-4769-bbff-cf2253017745)
