### ISSUE TITLE
Torch version confict

### ISSUE THREAD

**Issue by Kevin-Lee1299** [DekuLiuTesla/CityGaussian#57]
I have install the torch according to the guaidance :
python -m pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118

but when I install the other module in requirements
torch version conflict happens.
-------------------------------------------------
Requirement already satisfied: cmake in ./ENV_DIR/lib/python3.9/site-packages (from triton==2.0.0->torch<4.0,>=1.11.0->lightning==2.0.9.post0->-r requirements.txt (line 1)) (3.25.0)
Collecting shtab>=1.5.6
  Downloading shtab-1.7.1-py3-none-any.whl (14 kB)
Collecting eval-type-backport>=0.1.3
  Downloading eval_type_backport-0.2.0-py3-none-any.whl (5.9 kB)
Collecting h11>=0.8
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 KB 25.5 MB/s eta 0:00:00
Collecting lxml
  Downloading lxml-5.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 10.3 MB/s eta 0:00:00
Collecting torch<4.0,>=1.11.0
  Downloading torch-2.5.1-cp39-cp39-manylinux1_x86_64.whl (906.5 MB)
     ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.5/906.5 MB 2.3 MB/s eta 0:04:57

**Comment by zzz5y** [comment]
> I have install the torch according to the guaidance : python -m pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
> 
> ## but when I install the other module in requirements
> torch version conflict happens.
> Requirement already satisfied: cmake in ./ENV_DIR/lib/python3.9/site-packages (from triton==2.0.0->torch<4.0,>=1.11.0->lightning==2.0.9.post0->-r requirements.txt (line 1)) (3.25.0) Collecting shtab>=1.5.6 Downloading shtab-1.7.1-py3-none-any.whl (14 kB) Collecting eval-type-backport>=0.1.3 Downloading eval_type_backport-0.2.0-py3-none-any.whl (5.9 kB) Collecting h11>=0.8 Downloading h11-0.14.0-py3-none-any.whl (58 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 KB 25.5 MB/s eta 0:00:00 Collecting lxml Downloading lxml-5.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.0 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 10.3 MB/s eta 0:00:00 Collecting torch<4.0,>=1.11.0 Downloading torch-2.5.1-cp39-cp39-manylinux1_x86_64.whl (906.5 MB) ━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.5/906.5 MB 2.3 MB/s eta 0:04:57

Do you found the solution?

**Comment by rebecca0011** [comment]
Do you found the solution?

**Comment by zzz5y** [comment]
> Do you found the solution?

I think you can pass --no-deps in pip requirements.txt
