### ISSUE TITLE
question about the result of colmap 

### ISSUE THREAD

**Issue by Linkersem** [DekuLiuTesla/CityGaussian#58]
Hello, I also tried to calculate the colmap result of citymatrix, but the final sfm point cloud is not good. I would like to ask if you did any additional operations when calculating the sfm point cloud?

**Comment by DekuLiuTesla** [comment]
Hi, @Linkersem, I generate the COLMAP according to the given standard poses. Perhaps you could try our [script](https://github.com/DekuLiuTesla/CityGaussian/blob/11ece7d88627e3a85f0979b502dd500c526f4367/tools/transform_json2txt_mc_all.py).

**Comment by Linkersem** [comment]
@DekuLiuTesla Thanks for your  reply!  I downloaded the sci-art in the UrbanScene3D data and the colmap results you provided, but noticed that the image name in the colmap is inconsistent with the image name of the data I downloaded, am I downloading the wrong one, I downloaded the 35g size file of sci-art

**Comment by DekuLiuTesla** [comment]
@Linkersem Hi, could you please give some examples about the discrepancy?
