### ISSUE TITLE
OOM with mill19/building-pixsfm

### ISSUE THREAD

**Issue by Kevin-Lee1299** [DekuLiuTesla/CityGaussian#59]
when i run followed command，i got oom
bash scripts/run_citygs.sh

64G memory

is this process on server with 64G memory runnable？

**Comment by wdcici** [comment]
same question, with 72G memory 
when i run "bash scripts/run_citygs.sh" ,the memory usage rate has been consistently increasing and finally OOM

**Comment by leilei0330** [comment]
same question
![image](https://github.com/user-attachments/assets/a6f43ef5-d576-4e1c-8172-5d62471e26d9)

**Comment by leilei0330** [comment]
Has anyone had such a problem and solved it as well?

**Comment by DekuLiuTesla** [comment]
Hi, thanks for your valuable feedback. A possible solution is adjusting the max_cache_num in setting or downsample the images. Please try and see if the problem can be alleviated.

**Comment by leilei0330** [comment]
> Hi, thanks for your valuable feedback. A possible solution is adjusting the max_cache_num in setting or downsample the images. Please try and see if the problem can be alleviated.

Thanks for your reply, I've tried adjusting max_cache_num=256,128, and even set it to 0, but it didn't solve this problem, my machine is 4090D, and the memory is 64G, when I set max_cache_num=0, it will still say that 64G memory is full when the training iteration reaches about 1000, and then the train_large.py will be killed by the system, causing the program to not run normally.
It seems that the data loaded into the memory has not been cleaned up in time, so I tried to adjust the train_large.py to clean up the memory, but it did not succeed in cleaning, and the memory OOM still appeared

**Comment by bubuga** [comment]
I encountered a similar issue as well. My device is a 4090, and when the progress reaches around 40%, the program crashes. When I use nvidia-smi to check, I find that when the problem occurs, 24GB of GPU memory is full. Is it possible to run this code on a single 4090?"

**Comment by yzslab** [comment]
Take a look this comment: https://github.com/DekuLiuTesla/CityGaussian/issues/53#issuecomment-2466661417

**Comment by leilei0330** [comment]
> Take a look this comment: [#53 (comment)](https://github.com/DekuLiuTesla/CityGaussian/issues/53#issuecomment-2466661417)

It works for me，thank you very much!!!
