### ISSUE TITLE
Missing colmap when run mill19 dataset

### ISSUE THREAD

**Issue by Liuyan9527zns** [DekuLiuTesla/CityGaussian#6]
Awesome work and codes!
I want to run the CityGaussian on the Mill 19 dataset, following the suggestion. I have downloaded the raw images of rubble-pixsfm and building pixsfm from mega-nerf (https://storage.cmusatyalab.org/mega-nerf-data/building-pixsfm.tgz)with the provided colmap through your provided Google Drive (https://drive.google.com/file/d/1Uz1pSTIpkagTml2jzkkzJ_rglS_z34p7/view?usp=sharing).
When I run the data_proc_mill19.sh, an error happens: 
sh: 1: colmap : not found.(It seems that the colmap should exist in a newly created dictionary: distorted/database.db)

**Comment by DekuLiuTesla** [comment]
Thanks for your feedback. Seems that you need to install colmap first. Please follow https://colmap.github.io/install.html.

**Comment by Liuyan9527zns** [comment]
您好，您的邮件刘砚已经收到。我会及时处理并回复您。祝您生活愉快！

**Comment by DekuLiuTesla** [comment]
The provided Google Drive and Baidu NetDisk contains the COLMAP result we generated. You can just copy/paste the bin folders to train/val folder?
