### ISSUE TITLE
Clarification on Image Mapping Between COLMAP Results and Original MatrixCity Dataset

### ISSUE THREAD

**Issue by YaoXingbo** [DekuLiuTesla/CityGaussian#60]
Hi, @DekuLiuTesla ,thanks for your fantastic work
When i tried to prepare for the dataset under your instruction:
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/63e87973-89bb-41e3-b9af-c8a8eb4a147c">

I noticed that the MatrixCity dataset ([link](https://huggingface.co/datasets/BoDai/MatrixCity/tree/main/small_city/aerial)) is organized into 10 blocks, with each block containing several images. However, in the ./matrix_city_aerial/sparse/0/train/image.bin file from the COLMAP results you provided ([link](https://github.com/DekuLiuTesla/CityGaussian/blob/main/doc/data_preparation.md)), all the images are combined into a single file and are indexed sequentially from 1 to 5621.

Could you please clarify the correspondence between the images in your COLMAP results (indices 0-5621) and the original dataset blocks? Specifically, how can we map each image in the COLMAP results to its original block and file in MatrixCity?

Thank you again for your help and your contributions to the community!

**Comment by DekuLiuTesla** [comment]
Hi, @YaoXingbo. The provided link is the COLMAP for the whole scene, i.e. the combination of 10 officially divided blocks. And I'm afraid there is no direct way to map COLMAP to original block and file in MatrixCity. A more practical way is to regenerate the COLMAP with [our script](https://github.com/DekuLiuTesla/CityGaussian/blob/11ece7d88627e3a85f0979b502dd500c526f4367/tools/transform_json2txt_mc.py).

**Comment by DYL857857** [comment]
Could you please tell me what the error message is after running the bash script "data_proc_mc.sh"? It seems that there are many missing images in the test set and it doesn't match with the "images.bin" provided by the official version. As a result, the subsequent PSNR test metric is only 14.7. Are there any solutions to this problem?
