### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/mill19/rubble-pixsfm/train/data_partitions/rubble_c9_r4.npy'     How to sovle it？

### ISSUE THREAD

**Issue by Silent13417** [DekuLiuTesla/CityGaussian#64]

**Comment by DekuLiuTesla** [comment]
Hi, @Silent13417, you will have to first generate this partition file, as done [here](https://github.com/DekuLiuTesla/CityGaussian/blob/11ece7d88627e3a85f0979b502dd500c526f4367/scripts/run_citygs.sh#L26).
