### ISSUE TITLE
error in running rubble dataset

### ISSUE THREAD

**Issue by jjkingy** [DekuLiuTesla/CityGaussian#67]
@DekuLiuTesla
hi,thanks for your great work!
I have a problem when I try to use rubble dataset.
FileNotFoundError: [Errno 2] No such file or directory: '/home/yy/3DGS/CityGaussian/data/mill19/rubble-pixsfm/train/data/mill19/rubble-pixsfm/train/rgbs/001677.jpg'
This problem occured both in train_large.py and data_partition.py
could you provide some advice,thank you!

**Comment by sutao29** [comment]
I also encountered this problem, it may be a problem with the `ln` link. You can change the folder _rgbs_ to _images_.
