### ISSUE TITLE
Can city gaussian v1 or v2 handle the street view dataset like waymo/nuscenes?

### ISSUE THREAD

**Issue by zzz5y** [DekuLiuTesla/CityGaussian#68]
Hello, thanks for your great work!
curious about it,Because the official dataset seems to be BEV dataset

**Comment by DekuLiuTesla** [comment]
Hi, @zzz5y, a good question. We have validated our method on the street view of MatrixCity. However, to handle official datasets like waymo or nuscenes, dynamic objects (cars, pedestrians, etc) masks and appearance embedding are additionally required.

**Comment by zzz5y** [comment]
> Hi, @zzz5y, a good question. We have validated our method on the street view of MatrixCity. However, to handle official datasets like waymo or nuscenes, dynamic objects (cars, pedestrians, etc) masks and appearance embedding are additionally required.

Thanks for your reply!
And the validated result release in hugging face? I found the MatrixCity have 2 version trained 30k ply?

**Comment by DekuLiuTesla** [comment]
@zzz5y The street view validation is not included in the hugging face. But for V2, we would open-source it. The training configs are also coming soon.

**Comment by zzz5y** [comment]
> @zzz5y The street view validation is not included in the hugging face. But for V2, we would open-source it. The training configs are also coming soon.

Got it!Thank you for your quick reply and open-source and your amazing work!
