### ISSUE TITLE
Confuse about the MatrixCity street-view colmap result in BaiduNetDisk!

### ISSUE THREAD

**Issue by zzz5y** [DekuLiuTesla/CityGaussian#70]
Hi!I try to use the MatrixCity street-view colmap result in BaiduNetDisk to train base on CityGSv1,and then the result was bad.
I try to figure it out.And i found the colmap result was generate by 4075 images.
Can explain which part data do you use to generate the colmap result?Thank you

there are the all street-view data, I need to merge them to one folder?or just use one of them?
Looking forward to getting your reply and running the v2!

here is the folder in the Matrix-small-city:street-view 
├── small_city_road_down_train
├── small_city_road_horizon_train
├── small_city_road_outside_train
├── small_city_road_vertical_train

**Comment by DekuLiuTesla** [comment]
Hi, @zzz5y, your observation is correct. All four folders are combined together to get the final street-view COLMAP.  It undergoes following procedures:
```bash
mkdir data/matrix_city/street/train/block_A
mkdir data/matrix_city/street/test/block_A_test
python tools/transform_json2txt_mc_all_street.py --source_path data/matrix_city/street/train/block_A --intrinsic_path data/matrix_city/street/pose/block_A/transforms_train.json
python tools/transform_json2txt_mc_all_street.py --source_path data/matrix_city/street/test/block_A_test --intrinsic_path data/matrix_city/street/pose/block_A/transforms_test.json
python convert_cam.py -s data/matrix_city/street/train/block_A
python convert_cam.py -s data/matrix_city/street/test/block_A_test
```
However, this part is still in preparation, and detailed usage is going to be published in V2. If you do need this part, I think you can use the `tools/transform_json2txt_mc_all.py`  as a replacement for `tools/transform_json2txt_mc_all_street.py` to gather images. Then you can apply the provided COLMAP result.

**Comment by zzz5y** [comment]
> Hi, @zzz5y, your observation is correct. All four folders are combined together to get the final street-view COLMAP. It undergoes following procedures:
> 
> ```shell
> mkdir data/matrix_city/street/train/block_A
> mkdir data/matrix_city/street/test/block_A_test
> python tools/transform_json2txt_mc_all_street.py --source_path data/matrix_city/street/train/block_A --intrinsic_path data/matrix_city/street/pose/block_A/transforms_train.json
> python tools/transform_json2txt_mc_all_street.py --source_path data/matrix_city/street/test/block_A_test --intrinsic_path data/matrix_city/street/pose/block_A/transforms_test.json
> python convert_cam.py -s data/matrix_city/street/train/block_A
> python convert_cam.py -s data/matrix_city/street/test/block_A_test
> ```
> 
> However, this part is still in preparation, and detailed usage is going to be published in V2. If you do need this part, I think you can use the `tools/transform_json2txt_mc_all.py` as a replacement for `tools/transform_json2txt_mc_all_street.py` to gather images. Then you can apply the provided COLMAP result.

Got it!Thank you for your so fast reply and detail about the description and explain!Thanks a lot!

**Comment by DYL857857** [comment]
Could you please tell me how your "matrixcity_areial" dataset was processed? Based on the process of cityGaussianV2, I used the following command to prepare the data using the generated COLMAP results. The script data_proc_mc.sh shows that there are many missing images in the test set. Moreover, the official provided COLMAP results do not match the images in the test set.
