### ISSUE TITLE
Clarification on Block Configurations Used for Reported Results

### ISSUE THREAD

**Issue by NiranjanaaR** [DekuLiuTesla/CityGaussian#72]
Hi,
I’ve been working on GaussianCity (Matrix City) and followed the instructions in the repository, including using COLMAP results for training. I achieved the following metrics:

SSIM0.8769580721855164
PSNR29.84879493713379
LPIPS0.22399353981018066
Average FPS12.97981064685343
Min FPS7.742853978216725
Average Memory(M)13774.727997691043
Max Memory(M)15285.48046875
Number of Gaussians24753808

I used a block configuration of 2,2,1 during training. Could you confirm if the results reported in the paper (e.g., FPS, memory usage, etc.) were generated using this same block configuration, or if they were based on a different setup? If a different setup, can you please mention the block configuration details.

Thank you for your time and for making this amazing work accessible!

**Comment by DekuLiuTesla** [comment]
Hi, @NiranjanaaR , the memory usage is reported on 6x6x1 block division, as detailed in our official config. For FPS and memory usage, we test our model on 40G A100, and take average over 3-times running. Note that when testing these properties, there should be no extra process on GPU.
