### ISSUE TITLE
Strange result in street-view MatrixCity,Do you have any improving ideas?

### ISSUE THREAD

**Issue by zzz5y** [DekuLiuTesla/CityGaussian#73]
I run the citygs v1 in street-view Matrix,And got this strange results.Do you have any advice about improving the result?
And it would be the error by loading the images.txt?
I do some eding such as each 5 imgs loading 1.
```python
def read_extrinsics_text(path):
    """
    Taken from https://github.com/colmap/colmap/blob/dev/scripts/python/read_write_model.py
    Modified to exclude images with ID not divisible by 10.
    """
    images = {}
    with open(path, "r") as fid:
        while True:
            line = fid.readline()
            if not line:
                break
            line = line.strip()
            if len(line) > 0 and line[0] != "#":
                elems = line.split()
                image_id = int(elems[0])

                # # 排除 image_id 不能被 10 整除的情况
                # if image_id % 5 != 0:
                #     # 跳过当前条目并继续读取下一行
                #     fid.readline()  # 跳过 xys 和 point3D_ids 的数据行
                #     continue

                qvec = np.array(tuple(map(float, elems[1:5])))
                tvec = np.array(tuple(map(float, elems[5:8])))
                camera_id = int(elems[8])
                image_name = elems[9]
                elems = fid.readline().split()
                xys = np.column_stack([tuple(map(float, elems[0::3])),
                                       tuple(map(float, elems[1::3]))])
                point3D_ids = np.array(tuple(map(int, elems[2::3])))
                images[image_id] = Image(
                    id=image_id, qvec=qvec, tvec=tvec,
                    camera_id=camera_id, name=image_name,
                    xys=xys, point3D_ids=point3D_ids)
    return images
```

And here is the render_lod_pic
![img_v3_02hh_a1d11068-f36a-4a67-b345-acf5d81c41eg](https://github.com/user-attachments/assets/c3a66d97-d55b-412b-a642-5e81ac9d8d3e)
![2IDstKbSTP](https://github.com/user-attachments/assets/056ac23d-12c8-4cc2-984b-7d4a3e15b804)
![img_v3_02hh_47485954-a943-4cd3-b2c4-cdcade3a906g](https://github.com/user-attachments/assets/e86d04fe-b92b-4acc-8b29-519af77ab25c)
![img_v3_02hh_c6fa9764-6204-46e7-a281-e2c7785b35cg](https://github.com/user-attachments/assets/b016c525-a3f1-45b7-b9e9-fb328023d7bb)

**Comment by DekuLiuTesla** [comment]
Hi, @zzz5y, we notice that street view is extremely sparse, and therefore requires much longer iteration and densification interval, as well as lower position and scale learning rate. You can take this setting as a reference and accordingly scale it in parallel tuning stage. More details will be open-sourced in V2.
![image](https://github.com/user-attachments/assets/40dba32b-da01-4c13-89ce-cd5e8b17418a)

**Comment by zzz5y** [comment]
> Hi, @zzz5y, we notice that street view is extremely sparse, and therefore requires much longer iteration and densification interval, as well as lower position and scale learning rate. You can take this setting as a reference and accordingly scale it in parallel tuning stage. More details will be open-sourced in V2. ![image](https://private-user-images.githubusercontent.com/48622392/395428690-40dba32b-da01-4c13-89ce-cd5e8b17418a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjQ3NTIsIm5iZiI6MTczNDA2NDQ1MiwicGF0aCI6Ii80ODYyMjM5Mi8zOTU0Mjg2OTAtNDBkYmEzMmItZGEwMS00YzEzLTg5Y2UtY2Q1ZThiMTc0MThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA0MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzY2M0YmZkMzJlNzZhNGRjM2Y1MWE5ZTBmMmUyNDUwYWIzYjIzM2Y1OTE2ZGU3MDE5ZGY3Y2IyNmEzNGY5OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K9mY_i18Ryoe7QgmJhgeS7KX9MMAJDDhMPGACvD_x8A)

Thank you for your detailed explanation and answer, I will try it！

**Comment by DYL857857** [comment]
Could you please tell me how your "matrixcity_areial" dataset was processed? Based on the process of cityGaussianV2, I used the following command to prepare the data using the generated COLMAP results. The script data_proc_mc.sh shows that there are many missing images in the test set. Moreover, the official provided COLMAP results do not match the images in the test set.
