### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by AqsaUTA** [DekuLiuTesla/CityGaussian#76]
Thank you for your work. It is really very inspiring. I downloaded the colmap dataset you provided. It contains the bin files, but the images folder is missing. Should I download it from somewhere else?

**Comment by DekuLiuTesla** [comment]
Hi, @AqsaUTA, you can follow our [dataset instruction](https://github.com/DekuLiuTesla/CityGaussian/blob/main/doc/data_preparation.md) here to prepare data. It is worth noticing that we used UrbanScene3D-V1, which can be found [here](https://github.com/Linxius/UrbanScene3D).

**Comment by smart4654154** [comment]
> Hi, [@AqsaUTA](https://github.com/AqsaUTA), you can follow our [dataset instruction](https://github.com/DekuLiuTesla/CityGaussian/blob/main/doc/data_preparation.md) here to prepare data. It is worth noticing that we used UrbanScene3D-V1, which can be found [here](https://github.com/Linxius/UrbanScene3D).

Thank you very much for providing the colmap file. There are a total of 3019 test+train files in sciart. I successfully downloaded the data, which are also 3019 files, but they are divided into four folders. I guess you have renamed them. What are the specific rules for handling sciart and residence?@DekuLiuTesla
