### ISSUE TITLE
AttributeError: 'BlockedGaussian' object has no attribute 'cell_ids'

### ISSUE THREAD

**Issue by 7yzx** [DekuLiuTesla/CityGaussian#8]
When I run `python viewer.py --config config/mc_aerial_c36_lod.yaml`, it rises error `AttributeError: 'BlockedGaussian' object has no attribute 'cell_ids'`.
I noticed that lod_gs lacks [cell_ids](https://github.com/DekuLiuTesla/CityGaussian/blob/main/viewer.py#L279) but contains cell_idxs. 
This might be where the problem arises, but I'm not sure how to modify it.

**Comment by DekuLiuTesla** [comment]
Thanks for your feedback. It's a bug caused by improved LoD mechanism. We will soon fix it and update the code
